version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels: [dependencies]
    commit-message:
      prefix: build
      prefix-development: build
      include: scope
    groups:
      compatible-runtime-updates:
        dependency-type: production
        update-types: [minor, patch]
      compatible-development-updates:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels: [dependencies]
    commit-message:
      prefix: ci
      include: scope
    groups:
      compatible-action-updates:
        update-types: [minor, patch]
