[extend]
useDefault = true

[[allowlists]]
description = "Dépendances et artefacts générés non versionnés"
paths = [
  '''(^|/)\.git/''',
  '''(^|/)\.next/''',
  '''(^|/)coverage/''',
  '''(^|/)node_modules/''',
]
